// Copyright (C) 1991-2011 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 11.0 (Build Build 157 04/27/2011)
// Created on Sat Sep 29 15:05:23 2018

dac_bus_out dac_bus_out_inst
(
	.clk_in(clk_in_sig) ,	// input  clk_in_sig
	.dac_in0_i(dac_in0_i_sig) ,	// input [7:0] dac_in0_i_sig
	.dac_in0_q(dac_in0_q_sig) ,	// input [7:0] dac_in0_q_sig
	.r_ref_c(r_ref_c_sig) ,	// output  r_ref_c_sig
	.dac_sel(dac_sel_sig) ,	// output  dac_sel_sig
	.dac_clk(dac_clk_sig) ,	// output  dac_clk_sig
	.dac_wr(dac_wr_sig) ,	// output  dac_wr_sig
	.dac_reset(dac_reset_sig) ,	// output  dac_reset_sig
	.dac_data(dac_data_sig) 	// output [9:0] dac_data_sig
);

